language: ruby
bundler_args: --without production --quiet
install: ruby -S bundle install
script:
  - bundle exec rake dummy_app
  - bundle exec rake spec
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
rvm:
  - 2.2.2
  - 2.2.5
  - 2.3.0
  - ruby-head
