language: ruby
bundler_args: --without production --quiet
install: ruby -S bundle install
script:
  - bundle exec rake dummy_app
  - bundle exec rake spec
rvm:
  - 2.2.2
  - 2.2.5
  - 2.3.0
  - 2.3.1
